apiVersion: apps/v1
kind: Deployment
metadata:
  name: msdep
spec:
  selector:
    matchLabels:
      app: mskube
  replicas: 1
  template:
    metadata:
      labels:
        app: mskube
    spec:
      containers:
      - name: a1
        image: quay.io/kungliamg2593/alpine.ms
        ports:
        - containerPort: 25565
